on: [workflow_call]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - id: get-rust-version
        run: echo "rust_version=$(rustc --version)" >> $GITHUB_OUTPUT
        shell: bash
      - uses: actions/cache@v3
        with:
          path: |
            .bin/
            target/
            ~/.cargo/
          key: ${{ runner.os }}_${{ steps.get-rust-version.outputs.rust_version }}_${{ hashFiles('rust-toolchain.toml', 'Cargo.toml', 'Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}_${{ steps.get-rust-version.outputs.rust_version }}_
            ${{ runner.os }}_
      - run: npm ci
      - run: ./git_hooks/pre-commit
      - run: cargo run build
      - name: no_untracked
        run: |
          set -euxo pipefail
          if [[ `git ls-files --exclude-standard --others` ]]; then
            echo "untracked files detected"
            exit 1
          fi
      - name: no_modified
        run: |
          set -euxo pipefail
          if ! git diff --exit-code; then
            echo "modified files detected"
            exit 1
          fi
      - id: get_output_dir
        run: echo "output_dir=$(cargo run -- print-output-dir)" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v3
        with:
          name: build_output_dir
          path: ${{ steps.get_output_dir.outputs.output_dir }}
    outputs:
      output_dir: ${{ steps.get_output_dir.outputs.output_dir }}
